# Exclude files from pre-commit changes:
#
# * The generated OpenHashTab.rc resource script
# * Various VC++ configuration files.
#
exclude: 'OpenHashTab.rc|\.(filters|manifest|vcxproj)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=crlf
